/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-example-render.html
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../prism-element/prism-theme-default.d.ts" />

declare namespace ApiElements {

  /**
   * `api-example-render`
   *
   * Renders a JSON values using Prism highlighter.
   *
   * ## Styling
   *
   * `<api-resource-example-document>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-example-render` | Mixin applied to this elment | `{}`
   * `--code-block` | Mixin applied to the output block | `{}`
   */
  class ApiExampleRender extends Polymer.Element {

    /**
     * Data to render.
     */
    code: string|null|undefined;

    /**
     * Examples media type
     */
    mediaType: string|null|undefined;
    _dataChanged(code: any, mediaType: any): void;

    /**
     * Handles highlighting when code changed.
     * Note that the operation is async.
     */
    _codeChanged(code: String|null, mediaType: String|null): void;

    /**
     * Dispatches `syntax-highlight` custom event
     *
     * @param code Code to highlight
     * @param type Mime type of the code
     * @returns Highlighted code.
     */
    highlight(code: String|null, type: String|null): String|null;
  }
}

interface HTMLElementTagNameMap {
  "api-example-render": ApiElements.ApiExampleRender;
}
