/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   api-json-example-render.html
 */

/// <reference path="../polymer/types/polymer-element.d.ts" />
/// <reference path="../polymer/types/lib/utils/render-status.d.ts" />
/// <reference path="../prism-element/prism-theme-default.d.ts" />

declare namespace ApiElements {

  /**
   * `api-json-example-render`
   *
   * Renders a JSON values using Prism highlighter.
   *
   * ## Styling
   *
   * `<api-resource-example-document>` provides the following custom properties and mixins for styling:
   *
   * Custom property | Description | Default
   * ----------------|-------------|----------
   * `--api-json-example-render` | Mixin applied to this elment | `{}`
   * `--code-block` | Mixin applied to the output block | `{}`
   */
  class ApiJsonExampleEender extends Polymer.Element {

    /**
     * Data to render.
     */
    code: string|null|undefined;

    /**
     * Handles highlighting when code changed.
     * Note that the operation is async.
     */
    _codeChanged(code: String|null): void;

    /**
     * Dispatches `syntax-highlight` custom event
     *
     * @param code Code to highlight
     * @returns Highlighted code.
     */
    highlight(code: String|null): String|null;
  }
}

interface HTMLElementTagNameMap {
  "api-json-example-render": ApiElements.ApiJsonExampleEender;
}
